name: Create IssueHunt comment for opened issues
on:
  issues:
    types: [opened, reopened]
jobs:
  comment:
    name: Hello new contributor
    runs-on: ubuntu-latest
    steps:
     - name: Create IssueHunt comment for opened issues
       uses: goatandsheep/issuehunt-action@v1.0.0
